name: UtilsPlugin
version: ${project.version}
main: com.wagologies.utilsplugin.UtilsPlugin
commands:
  ban:
    usage: /ban <player>
    description: Ban a player
    permission: utils.ban
  vanish:
    usage: /vanish [<player>]
    description: Vanish from everyone
    permission: utils.vanish
  fly:
    usage: /fly [<player>] [<speed>]
    description: Enables/Disables flight in all gamemodes
    permission: utils.fly
  invsee:
    usage: /invsee <player> [<main|ender>]
    description: See player inventory
    permission: utils.invsee
  heal:
    usage: /heal [<player>]
    description: Heal yourself or a player
    permission: utils.heal
  god:
    usage: /god <player>
    description: Makes you invincible
    permission: utils.god
  items:
    usage: /items
    description: Gives you quick access to interesting items
    permission: utils.items
  warp:
    usage: /warp <world>
    description: Teleports you between worlds
    permission: utils.warp
  loadworld:
    usage: /loadworld <worldName>
    description: Loads an existing world
    permission: utils.load
  pvp:
    usage: /pvp
    description: Opens a config menu for pvp rules
    permission: utils.pvp
  createnpc:
    usage: /createnpc
    permission: utils.npc.create
  lookat:
    usage: /lookat
    permission: utils.npc.lookat